# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174b8a06d1be78ce03916c9f9c6664219840f16f429dac6ea1319204ea596435a2832434d89ecb8f8f19d53d0ccbb2d93f308d905d568d8350bcd2df933203f5

test:
  secret_key_base: fd27b9648de717e42b29b8b3ed841071ee69e2e3263370dd0266fa7a360f8aac701e4aca4048f2954490782ec22d0ffe6026d9d539e0cc42360b88bc1897276c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
